import LocalizedStrings from 'react-localization';
import React from 'react';

let localStrings = new LocalizedStrings({
    fr: {
        closeUntil: "Les commandes sont indisponible jusqu'a: {0}\"",
        chooseEsta: "Choisir l'établissement",
        chooseEsta1: "Vous avez choisi l'établissement {0} vous pouvez changer à tous moment en clickant sur l'icone ",
        chooseEsta2: " Dans la barre d'action du haut",
        noSlotToday: "Pas de créneaux possibles aujourd'hui",
        pickupOnSpot: "A recupérer sur place",
        onTheSpot: "Sur place",

        editOptions: "Changer les options",
        editProductMenu: "Changer les produits",
        pendingPointsGain: "Vous gagnez {0} points avec cette commande",
        use: "Utiliser",
        useYouPoints: "Utilisez vos points",
        useYouPointsDetail: "Vous possedez {0} points de fidelité (={1}). Vous pouvez utiliser vos points et économiser <strong>{1}</strong> avec cette commande",

        loyalty: "Fidelité",
        bravo: "Bravo",
        loyaltyPoints: "Mes points de fidelités",
        loyaltyPointsEarned: "Felicitation Vous avez cumulé {0} points de fidelité",
        loyaltyPointsSpent: "Vous avez depensé {0} points de fidelités",
        loyaltyPointNumber: "{0} points",
        loyaltyRemainsToSpent: "Plus que {0} points pour pouvoir en profiter !!",
        loyaltyCanUsuPoints: "Vous points sont utilisables !!!",
        useLoyaltyPoints: "Utiliser {0} points et economiser {1}",
        usedLoyaltyPoints: "Vous Economisez {0} avec vos {1} points de fidelités (Les prix rééls appliqué peuvent variés de quelques centimes)",
        discountsLoyaltyName: "-{0} avec vos {1} points de fidelités",

        discountPointRemoved: "Promotion desactivé",
        discountPointRemovedDetail: "Votre promotion a été desactivée car le montant de votre panier a changé. Vous pouvez toujours réappliquer votre promotion sur votre nouveau panier",

        myMainInfo: "Mes informations principales",
        myRequirements: "Mes exigences",
        myOptions: "Mes options",
        leaveCommentOnGoogle: "Laissez nous un commentaire sur google",
        ownerResponse: "Response du propriétaire",
        update: "Mettre a jour",
        deleteReview: "Supprimmer cet avis",
        editReview: "Editer cet avis",
        writeReviewHere: "Ecrire votre avis ici",
        yourReview: "Votre avis sur le produit",
        yourRating: "Votre note",
        postReview: "Poster le l'avis",
        writeReview: "Donnez votre avis sur ce produit",
        writeReviewFirst: "Soyez le premier a donnez votre avis sur ce produit",
        updateReview: "Mettez a jour votre avis sur ce produit",
        reviews: "Avis",
        thisIspresent: "Offert",
        noThanks: "Non merci",
        priceWithOffer: "Prix avec l'offre: {0}",
        saveWithOffer: "Economie avec l'offre:-{0}%",
        specialOffer: "Profitez de l'offre \"{0}\" pour seulement  {1} de plus et économisez sur les produits suivants",
        specialOfferNoSavePrice: "Profitez de l'offre \"{0}\" et économisez sur les produits suivants",
        dealApplied: "offre appliquée",
        dealAppliedDetail: "L'offre spéciale {0} a été appliqué à votre panier vous économisez {1} Eur",
        noAllergens: "Ce produit ne contient aucun allergène alimentaire majeur",
        allergensList: "Liste des allergènes majeurs contenus dans ce produit:",
        seeDetail: "Voir le detail",
        deliveryHourAndPlace: "Horaires d'ouverture et emplacement",
        deliveryHourAndPlaceDesc: "Consultez nos horaires d'ouverture et notre emplacement",


        mobileCategory: "Catégories",
        noAdresseFound: "Continuer a saisir du texte pour trouver votre adresse...",
        fillAddressDelivery: "Saisir ici une adresse de livraison",
        //fillAddressDeliveryConnectedIf: "Ou saisir ici une adresse de livraison personalisée",
        fillAddressDeliveryConnected: "Ou saisir ici votre adresse de livraison",

        fillAddress: "Saisir ici votre adresse",
        fillAddressName: "Saisir ici le nom de votre adresse (Travail, Maison, ...)",

        couponNotValidAnymore: "Votre coupon {0} n'est plus disponible et a été supprimé",
        couponNotValidAnymoreTitle: "Coupon invalide",

        invalidCouponConsumed: "Vous avez déjà consommé ce coupon !",
        invalidCouponBadEsta: "Ce coupon n'est pas valide pour l'etablissement selectioné !",
        invalidCouponTooSoon: "Ce coupon n'est pas encore valide !",
        invalidCouponTooLate: "Ce coupon n'est plus valide !",
        invalidCouponPrice: "Votre panier n'atteinds pas la somme minimale requise de {0} {1}",
        couponAlreadyInUse: "Un coupon est déja en cours d'utilisation",
        wrongCouponCode: "Le code {0} n'est pas valide",
        codeApplied: "Code {0} appliqué",
        applyCouponCode: "Appliquer mon code",
        connectApplyCouponCode: "Connectez-vous pour appliquer votre code",
        cannotApplyCouponCodeWithLoyalty: "Imcompatible avec les points de fidelités",
        connectWriteComment: "Connectez-vous pour laisser votre avis",
        IHaveACouponCode: "J'ai un code promo",
        IUnderstand: "J'ai compris",
        setClosestEsta: "Sélectionnez l'établissement le plus proche",
        selectEsta: "Sélectionnez votre établissement",
        selectEsta2: "Sélectionner un établissement",
        changeEsta: "Changer d'etablissement",
        selectedEsta: "Etablissement selectionné",
        cgvAccept: "J'accepte les termes et conditions",
        commercialAgreementAccept: "J'accepte de recevoir des proposition commerciales par email",
        seeCgvAccept: "Voir les termes et conditions",
        legalNotice: "Mentions légales",
        cgv: "Conditions générales de vente",
        unavailableInDelivery: "Indisponible en livraison",
        allCat: "toutes categories",
        categoryTitleDef: "{0} categorie {1}",
        categoryDescriptionDef: "{0} vous propose les produits de la catégorie {1}",
        siteUnavailable: "Le site n'est pas disponible",
        siteUnavailableDetail: "Contactez le restaurant pour plus d'information",

        loginError: "Erreur d'authentification",
        detail: "Detail",
        productRestricted: "Produit indisponible dans ce contexte",
        cartRestricted: "Produits indisponibles",
        cartRestrictedDetail: "Certains produits deviennent indisponibles dans ce contexte cliquez sur detail pour obtenir l'explication",

        close: "Fermer",
        unavailableDay: "Indisponible pour le {0}",
        deliveryUnable: "Indisponible pour {0}",
        bookingTimeUnable: "Indisponible pour pour le moment",
        deliveryZone: "Indisponible dans cette zone de livraison",
        bookingSameDay: "La date de commande et la date de retrait/livraison doivent être égales",

        deliveryDistanceMin: "La distance jusqu'à l'établissement doit être supérieure à {0} kms",
        deliveryDistanceMax: "La distance jusqu'à l'établissement doit être inférieure à {0} kms",
        deliveryDistanceMinMax: "La distance jusqu'à l'établissement doit comprise entre {0} et {1} kms",

        priceMin: "Le prix total de la commande doit être supérieure à {0} {1}",
        priceMax: "Le prix total de la commande doit être inférieure à {0} {1}",
        priceMinMax: "Le prix total de la commande doit être compris entre {0} et {1} {2}",

        dateMin: "La date de commande doit être apres le {0}",
        dateMax: "La date de commande doit être avant le {0}",
        dateMinMax: "La date de commande doit être  comprise entre le {0} et le {1}",

        hourMin: "L'heure de commande doit être apres {0}",
        hourMax: "L'heure de commande doit être avant le {0}",
        hourMinMax: "L'heure de commande doit être  comprise entre le {0} et le {1}",

        maxItems: "Nombre d'elements maximum atteind",

        restrictionApplies: "Ce produit n'est pas toujours disponible",
        noAvail: "Désolé il n'y a pas de créneau disponible, essayez à un autre moment",
        selectDeliveryModesToGetSlots: "Selectionner un mode de livraison pour afficher les creneaux.",
        shareOnFacebook: "Partager ce produit sur facebook",
        back: "Retour",
        poweredBy: "Site construit avec La toque magique",
        phoneInternational: "Numéro de téléphone au format international +...",
        demoDisclaim: "Ceci est un site de démonstration aucune commande ne sera honorée",
        manageMyAdresses: "Gérer mes adresses",
        updateAddtionalInformation: "Mettre à jour les informations additionnelles",
        updateCustomerDeliveryInformation: "Mettre à jour les informations de livraison de cette adresse",
        defineMainAdress: "Définir mon adresse principale",
        useMyAdresses: "Utiliser mes adresses",
        useCustomAdresses: "Utiliser une autre adresse",

        backToHome: "Revenir à la page d'accueil",
        backNav: "Revenir en arriere",

        personalInformation: "Saisir vos informations de commandes",
        seeInfo: "Voir les infos utiles",
        bookingadditionalInformationNotes: "Note pour la commande",
        bookingadditionalInformationNotesPlaceHolder: 'Indiquez par exemple "Viande bien cuite" ou "Sans mayonnaise", ...',
        bookingadditionalInformation: "Information pour la livraison ou demande spécifique pour la commande",

        bookingadditionalInformationExample: "Code immeuble, étage, interphone,…",
        closed: "Etablissement exceptionellement fermé",
        new: "Nouveau",
        starProducts: "Top produits",
        mailSent: "Email envoyé",
        mailSentDetail: "Un email avec le detail de votre commande a été envoyé à {0}",
        closingPeriod: "Du {0} au {1}",
        weekDay: "Jour de la semaine",
        closingDays: "Jours de fermeture",
        schedules: "Horaires",
        place: "Notre emplacement",
        openingHours: "Horaires d'ouverture",
        contactUs: "Nous contacter",

        unavailable: "Indisponible",
        modifyMyAccount: "Modifier mon compte",
        homePageTitle: "Accueil",
        infoContactPageTitle: "Informations utiles",
        shopPageTitle: "Commander",
        profilePageTitle: "Mon compte",
        contactInfoPageTitle: "Infos utiles",
        openingAndLocation: "Emplacements et horaires",
        cartPageTitle: "Voir mon panier",

        creditCardDetail: "Detail de carte de credit",
        paymentCreditCard: "Payer par carte bancaire maintenant",
        paymentDelivery: "Payer à la réception",

        paymentMethod: "Méthode de paiement",
        paymentMethodsForPickup: "Sélectionnez vos méthodes de paiement pour le paiement à la réception",

        saveChange: "Sauvegarder les changements",
        backToProfile: "Retour à mon profil",
        notificationInfo: "Afin de recevoir des notifications lorsque votre commande est prête vous pouvez activer les notifications pour ce site, dans la barre de tâche de votre navigateur",
        activateNotification: "Activer les notifications",
        home: "Home",
        orderCount: "Commandes",
        awaitingOrders: "Commandes en attente",
        myProfile: "Mon profile",
        seeMyOrderDetail: "Voir le status de ma commande",
        orderCompletedThanks : "Merci d'avoir commandé avec {0}",
        orderCompleted: "Commande confirmée",
        refresh: "Actualiser",
        deliveryEstimateDate: "Date de livraison estimée: {0}",
        orderDate: "Date de commande",
        deliveryHour: "Horaire de livraison prévu",
        pickupHour: "Horaire de récuperation prévu",
        orderDetail: "Detail de la commande",
        total: "Total",
        mandatorySelection: "(Sélection obligatoire)",

        optionListWithLimitMinMax: "Option {0} sélectionnez minimum {1} option(s) et maximum {2} {3}",
        optionListWithLimitMin: "Option {0} sélectionnez minimum {1} option(s) {2}",
        optionListWithLimitMax: "Option {0} sélectionnez maximum {1} option(s) {2}",
        optionListWithLimit: "Option {0} {1}",

        mandatoryOption: "(obligatoire)",
        sendLinkAgain: "Ré-envoyer le lien d'activation",
        backToLoginPage: "Revenir a la page de connection",
        createYourAccount: "Créer mon compte",
        havingAnAccount : "J'ai déjà un compte ?",
        orderAgain: "Commander a nouveau",
        contentDeal: "Contenu du menu",
        modify: "Modifier",
        editProfile: "Editer mon compte",
        purchaseDate: "Date de commande",
        orderNumber: "Numero de commande",
        orderNumberMobile: "N°",
        orderId: "Identifiant de commande",
        status: "statut",
        dashBoard: "Tableau de bord",
        orders: "Commandes",
        warning: "Attention",
        infoMessage: "Information",
        information: "Information",
        viewAllCat: "Voir toutes les catégories",
        backToCart: "Revenir au panier",

        phone: "Téléphone",
        bookWithoutAccount: "Commander sans creer de compte",
        profileInformation: "Information de compte",
        tooFarAddress: "Adresse en dehors de la zone de livraison",
        formatDuration: "HH [heure(s) et] mm [minute(s)]",
        formatDurationNoHour: "mm [minute(s)]",

        //myAdresses: "Mes adresses",

        distanceTime: " distance jusqu'à l'établissement: {0} km / {1}",
        distanceOnly: " distance jusqu'à l'établissement: {0} km ",
        timeSlot: "Créneau de réservation",
        pickupSlot: "Créneau de récupération",
        selectDeliveryTimeSlot: "Sélectionner un créneau de livraison",
        selectPickupTimeSlot: "Sélectionner un créneau de récupération",
        priceToPay: "Montant à payer",
        pricePaid: "Montant payé",
        pendingPayment: "Paiement en attente",
        remainingToPay: "Reste a payer: {0}",

        totalNoTax: "Total hors taxes",
        totalCharge: "Total frais",
        totalTax: "Total TVA",
        savedCode: "Économie avec la promo: {0}",
        couponCode: "code promo: {0}",
        couponCodeSingle: "code promo",
        pointsSave: "{0} points",

        totalTTC: "Total TTC",
        deliveryFee: "Frais de livraisons",
        deliveryFeeExternal: "Frais de livraisons partenaire externe",
        totalFee: "Total frais",

        deliverToOtherAddress: "Livrer a une autre adresse",
        validateAdress: "Valider l'adresse",
        clickAndCollect: "A récupérer sur place (Click N Collect)",
        clickAndCollectSubTitle: "Récupérez votre commande sans attendre sur votre point de vente",
        delivery: "Livraison",
        deliverySubTitle: "Faites-vous livrer chez vous, au bureau ou encore chez des amis.",
        deliveryMode: "Mode de livraison",
        selectDeliveryMode: "Choississez votre mode de livraison",
        cart: "Panier",
        cartDesc: "Contenu de votre panier",
        confirm: "Confirmation",
        confirmAction: "Confirmer",
        order: "Commande",
        categories: "Catégories",
        menu: "Carte",
        tags: "Tags",
        selectDeal: "Choisir les produits",
        choose: "Choisir",
        cancel: "Annuler",
        next: "Selectionner le produit suivant",
        select: "Selectionner le produit",
        addMenuToCart: "Ajouter le menu au panier",
        checkOutNow: "Passer la commande",
        checkOutNowAndPayLater: "Commander et payer {0}€ à la réception",
        checkOutNowAndPayCard: "Commander et payer {0}€ maintenant",
        orderFree: "Commander gratuitement !!",
        continueShopping: "Ajouter d'autres produits",
        viewCart: "Voir le detail du panier",
        emptyBasket: "Votre panier est vide",
        cartItemNumber: "{0} produits dans le panier",
        selectOptions: "Options",
        deals: "Menu et offres",
        sortBy: "Trier par ",
        ourProducts: "Nos produits",
        view: "Vue",
        allCategories: "Toutes les catégories",
        category: "Catégorie",
        categorie: "Categories",
        searchResults: 'Résultats de recherche pour: "{0}"',
        searchFor: "Rechercher un produit ....",
        continueWithGoogle: "Identification avec google",
        continueWithFaceook: "Continuer avec facebook",
        profile: "Profil",
        profileDesc: "Information de votre Profil",
        myAccount: "Mon compte",
        myOrders: "Mes commandes",

        myAddresses: "Mes adresses",
        addNewAddress: "Ajouter une nouvelle adresse",
        modifyAddress: "Modifier une adresse",
        modifyMainAddress: "Modifier mon adresse principale",
        mainAddress: "Adresse principale",
        backToAdress: "Retour à mes adresses",
        nameAddress: "Nom de l'adresse",
        updateMainAddress: "Mettre à jour mon adresse principale",
        updateAddress: "Mettre à jour l'adresse",
        createAddress: "Créer l'adresse",


        account: "Compte",
        logout: "Se déconnecter",
        password: "Mot de passe",
        reTypePassword: "Repeter le mot de passe",
        logEmailAndPassword: "Identifiez vous",
        dontHaveAccount: "Vous n'avez pas de compte?",
        signup: "Creer un compte",
        resetPassword: "Réinitialiser le mot de passe",
        forgotPassword: "Mot de passe oublié",
        address: "Adresse",
        deliveryAdress: "Adresse de livraison",
        selectDeliveryAdress: "Choisir l'adresse de livraison",
        email: "Email",
        firstName: "Prenom",
        lastName: "Nom",
        termsAndConditions: "Termes et conditions",
        activateAccount: "Activer mon compte",
        completeAccount: "Compléter mon compte",
        fillInfoToContinue: "Renseignez les champs pour continuer",
        login: "Se connecter",
        continueWithoutAccount: "Non Merci, Prendre ma commande sans créer de compte",
        bySigningTermsAndConditions: "En cochant cette case vous acceptez les termes et conditions",
        requiredField: "Le champ {0} est obligatoire",
        addToCart: "Ajouter au panier",
        updateCart: "Modifier le panier",
        selectOptionsDetail: "Selectionner {0}",
        description: "Description",
        additionalInformation: "Information additionnelle",
        customerDeliveryInformation: "Information additionnelle pour la livraison",
        customerDeliveryInformationPlaceHolder: 'Indiquer ici par exemple votre code porte, ou d\'autres indications pour le livreur',
        priceAsc: "Prix croissant",
        priceDesc: "Prix décroissant",

        orderSourceOnline: "Commande internet",
        orderSourceOffline: "Commande restaurant",

        deliveryStatusOnGoing: "On going",
        deliveryStatusNotStarted: "Not started",
        deliveryStatusDone: "Done",

        orderStatus: "Statut de la commande",
        orderStatusNew: "Nouveau",
        orderStatusPreparation: "Prepararation",
        orderStatusReady: "Pret",
        orderStatusDelivering: "En livraison",
        orderStatusComplete: "Finalisé",
        orderStatusFinished: "Terminé",

        paymentMethodsOffline: "Offline payment methods",
        paymentMethodsOnline: "Online payment methods",
        paymentMethodCash: "Espèce",
        paymentMethodCC: "Carte",
        paymentMethodCheque: "Chèque",
        paymentMethodTicket: "Ticket restaurant",
        paymentMethodStripe: "Stripe",

        day_0 : "Lundi",
        day_1 : "Mardi",
        day_2 : "Mercredi",
        day_3 : "Jeudi",
        day_4 : "Vendredi",
        day_5 : "Samedi",
        day_6 : "Dimanche",

        lunch: "dejeuner",
        dinner: "dinner",

        hrorderStatusNew: "Nouveau",
        hrorderStatusReceived: "Reçu",
        hrorderStatusAccepted: "Accepté",
        hrorderStatusInPreparation: "En preparation",
        hrorderStatusAwaitingShipment: "Pret a livrer",
        hrorderStatusAwaitingCollection: "Pret a récuperer",
        hrorderStatusinDelivery: "Livraison en cours",
        hrorderStatusCompleted: "Finalisé",
        orderStatusPendingPayment: "En attente de paiement",
        hrorderStatusRejected: "Rejetée",
        hrorderStatusCancelled: "Annulé",
        hrorderStatusDeliveryFailed: "Echec livraison",

        stuartFollowUrl: "Lien de suivi Stuart",
        stuartFollowUrlContent: "Clicker ici pour suivre la progression de votre commande",

        stuartLoadingTitle: "Verification de possibilité de livraison",
        stuartLoading: "Nous verifions si la livraison est possible",


        check: {
            fieldRequired: "Le champ {0} est obligatoire",
            required: "Obligatoire",
            requiredField: "Champ obligatoire",
            badPhoneFormat: "Numéro de téléphone invalide",
            termsAndConditionsMandatory: "Vous devez accepter les termes et conditions",
            passwordsMatch: 'Les mots de passe doivent être les mêmes',
            reTypePassword: "Fournir le mot de passe une nouvelle fois",
            invalidEmail: "eMail invalide",
            noDaySetting: "Pas de créneau configuré",

            noSelectPaymentMethod: "Aucune méthode de paiments selectionné",
            noSelectSlotMethod: "Aucune Créneau selectionné",
            noDeliveryAdress: "Aucune adresse de livraison selectionné",
            maxDistanceReached: "L'adresse est en dehors de la zone",
            noItemInCart: "Aucun produits dans le panier",
            badContactInfo: "Information de contact invalides",
            deliveryMinPrice: "Montant insufisant pour livraison",
            pleaseAcceptCgv: "Merci d'accepter les termes et conditions",
        },

        info: {
            resetPassword: "Un email a été envoyé a {0} pour réinitialiser le mot de passe",
            checkAddessInfo: "Afin de savoir si votre etes eligible à la livraison à domicile, merci de fournir une adresse",
            connectToOrder: "Afin de garder une trace de vos commandes et de garantir un meilleur suivi, nous vous conseillons d'effectuer la commande en mode connecté. Si vous avez un compte Google, Cela ne prendra que quelques secondes !!",
        },

        warningMessage: {
            noMainAddDefined: "Votre adresse principale n'est pas définie",
            maxDistanceDelivery: "L'adresse sélectionnée est en dehors de la zone de livraison mais vous pouvez toujours commander en mode click and collect",
            maxDistanceDeliveryOk: "L'adresse sélectionnée est dans la zone de livraison",
            maxDistanceDeliveryOkZone: "L'adresse sélectionnée est dans la zone de livraison ({0})",
            selectValidDeliveryAddressAndSchedule: "Sélectionner une adresse de livraison valide et un créneau de réservation",
            optionMandatory: "Merci de choisir les options requises",
            minimalPriceForDeliveryNoReached: "La livraison n'est disponible que pour un montant minimum de {0} €",
            deliveryUnavailable: "Livraison non disponible",
            paymentIssue: "Un problème est survenu avec votre paiement",
            profileNotActivated: "Votre compte n'est pas encore actif, vérifier votre email et activer votre compte en cliquant sur le lien contenu dans le mail d'activation, puis connectez-vous de nouveau",
            deliveryFeeOccurs: "Les frais de livraison a votre charge s'élèvent à {0} {1}",
            stuartDeliveryPossible: "Livraison disponible !",
            stuartDeliveryImpossible: "Livraison non disponible !",
            stuartConnectionIssue: "Nous rencontrons des problemes pour communiquer avec le service de livraison externe",
            stuartOutOfRange: "L'addresse de livraison est en dehors de la zone courverte",
        },
        notif: {
            accountCreated: "Compte cree",
            dealAddedToCart: "Offre ajouté au panier",
            productAddedToCart: "Produit ajouté au panier",
            activationEmailSentNotif: "Email d'activation envoye a {0}, verifier votre email, activez le compte puis connectez-vous de nouveau",
        },

        notifForBackEnd: {
            orderCreated: "Nouvelle Commande en ligne: {0}"
        },

        errorMessages: {
            accountAlreadyExists: "Ce compte est déjà référencé, essayer de vous connecter directement en utilisant cet email",
            wrongPassword: "Mot de passe invalide",
            noUserEmail: "Aucun compte trouvé avec cet email"
        },

        confirmMessage: {
            deleteAddress: 'Etes-vous sûr de vouloir supprimer cette adresse ?',
            deleteReview: 'Etes-vous sûr de vouloir supprimer cet avis ?',
        },

        emailTemplate: {
            passwordReset: "Cliquer <a href='{0}'>ici</a> pour réinitialiser votre mot de passe {1}",
            activateEmail: "Cliquer <a href='{0}'>ici</a> pour activer votre compte {1}",
            passwordResetSubject: "Réinitialiser votre mot de passe {0}",
            activateEmailSubject: "Activer votre compte {0}",
        },
        allergens: "Allergènes",
        allergenTypes: {
            gluten: "Gluten",
            shellfish: "Crustacés",
            egg: "Oeuf",
            fishes: "Poissons",
            peanuts: "Arachides",
            soy: "Soja",
            milk: "Lait",
            nuts: "Fruits à coques",
            celery: "Celeri",
            mustard: "Moutarde",
            sesameSeeds: "Graines de sésame",
            sulfurDioxideSulphites: "Anhydride sulfureux et sulfites",
            lupine: "Lupin",
            molluscs: "Mollusques"
        },


    },
    en: {
        closeUntil: "Orders are unavailable until: {0}",
        "chooseEsta": "Choose the establishment",
        "chooseEsta1": "You have chosen the establishment {0} you can change at any time by clicking on the icon",
        "chooseEsta2": "In the top action bar",
        "noSlotToday": "No slots possible today",
        "pickupOnSpot": "To be picked up on site",
        "onTheSpot": "On the spot",
        "editOptions": "Change options",
        "editProductMenu": "Change products",
        "pendingPointsGain": "You earn {0} points with this order",
        "use": "To use",
        "useYouPoints": "Use your points",
        "useYouPointsDetail": "You have {0} loyalty points (={1}). You can use your points and save <strong>{1}</strong> with this order",
        "loyalty": "Loyalty",
        "bravo": "Bravo",
        "loyaltyPoints": "My loyalty points",
        "loyaltyPointsEarned": "Congratulations You have accumulated {0} loyalty points",
        "loyaltyPointsSpent": "You have spent {0} loyalty points",
        "loyaltyPointNumber": "{0} points",
        "loyaltyRemainsToSpent": "Only {0} points left to enjoy!",
        "loyaltyCanUsuPoints": "Your points can be used!!!",
        "useLoyaltyPoints": "Use {0} points and save {1}",
        "usedLoyaltyPoints": "You save {0} with your {1} loyalty points (The actual prices applied may vary by a few cents)",
        "discountsLoyaltyName": "-{0} with your {1} loyalty points",
        "discountPointRemoved": "Promotion disabled",
        "discountPointRemovedDetail": "Your promotion has been deactivated because the amount of your basket has changed. You can always reapply your promotion to your new basket",
        "myMainInfo": "My main information",
        "myRequirements": "My requirements",
        "myOptions": "Mes options",
        "leaveCommentOnGoogle": "Leave us a comment on google",
        "ownerResponse": "Owner's Response",
        "update": "To update",
        "deleteReview": "Delete this review",
        "editReview": "Edit this review",
        "writeReviewHere": "Write your review here",
        "yourReview": "Your opinion on the product",
        "yourRating": "Your rating",
        "postReview": "Post the review",
        "writeReview": "Write a review on this product",
        "writeReviewFirst": "Be the first to review this product",
        "updateReview": "Update your opinion on this product",
        "reviews": "Avis",
        "thisIspresent": "Free",
        "noThanks": "No Thank you",
        "priceWithOffer": "Price with offer: {0}",
        "saveWithOffer": "Savings with the offer:-{0}%",
        "specialOffer": "Take advantage of the \"{0}\" offer for only {1} more and save on the following products",
        "specialOfferNoSavePrice": "Take advantage of the \"{0}\" offer and save on the following products",
        "dealApplied": "offer applied",
        "dealAppliedDetail": "The special offer {0} has been applied to your cart you save {1} Eur",
        "noAllergens": "This product does not contain any major food allergens",
        "allergensList": "List of major allergens contained in this product:",
        "seeDetail": "See details",
        "deliveryHourAndPlace": "Opening hours and location",
        "deliveryHourAndPlaceDesc": "Check our opening hours and location",
        "mobileCategory": "Categories",
        "noAdresseFound": "Continue typing to find your address...",
        "fillAddressDelivery": "Fill a delivery address here",
        "fillAddressDeliveryConnected": "Or fill your delivery address here",
        "fillAddress": "Fill your address here",
        "fillAddressName": "Enter the name of your address here (Work, Home, ...)",
        "couponNotValidAnymore": "Your coupon {0} is no longer available and has been deleted",
        "couponNotValidAnymoreTitle": "Coupon invalide",
        "invalidCouponConsumed": "You have already consumed this coupon!",
        "invalidCouponBadEsta": "This coupon is not valid for the selected establishment!",
        "invalidCouponTooSoon": "This coupon is not yet valid!",
        "invalidCouponTooLate": "This coupon is no longer valid!",
        "invalidCouponPrice": "Your cart does not reach the required minimum amount of {0} {1}",
        "couponAlreadyInUse": "A coupon is already in use",
        "wrongCouponCode": "Code {0} is not valid",
        "codeApplied": "Code {0} applied",
        "applyCouponCode": "Apply my code",
        "connectApplyCouponCode": "Log in to apply your code",
        "cannotApplyCouponCodeWithLoyalty": "Not compatible with loyalty points",
        "connectWriteComment": "Log in to leave your opinion",
        "IHaveACouponCode": "I have a promo code",
        "IUnderstand": "Got it",
        "setClosestEsta": "Select the nearest establishment",
        "selectEsta": "Select your establishment",
        "selectEsta2": "Select an establishment",
        "changeEsta": "Change establishment",
        "selectedEsta": "Selected establishment",
        "cgvAccept": "I accept the terms and conditions",
        "commercialAgreementAccept": "I agree to receive commercial proposals by email",
        "seeCgvAccept": "See terms and conditions",
        "legalNotice": "Legal Notice",
        "cgv": "Terms of Sales",
        "unavailableInDelivery": "Unavailable in delivery",
        "allCat": "all categories",
        "categoryTitleDef": "{0} categories {1}",
        "categoryDescriptionDef": "{0} offers you the products of the category {1}",
        "siteUnavailable": "The site is not available",
        "siteUnavailableDetail": "Contact the restaurant for more information",
        "loginError": "Authentification error",
        "detail": "Detail",
        "productRestricted": "Product unavailable in this context",
        "cartRestricted": "Unavailable products",
        "cartRestrictedDetail": "Some products become unavailable in this context click on detail to get the explanation",
        "close": "Close",
        "unavailableDay": "Unavailable for {0}",
        "deliveryUnable": "Unavailable for {0}",
        "bookingTimeUnable": "Unavailable for the moment",
        "deliveryZone": "Not available in this delivery area",
        "bookingSameDay": "Order date and pickup/delivery date must be equal",
        "deliveryDistanceMin": "Distance to property must be greater than {0} kms",
        "deliveryDistanceMax": "Distance to property must be less than {0} kms",
        "deliveryDistanceMinMax": "The distance to the property must be between {0} and {1} kms",
        "priceMin": "The total price of the order must be greater than {0} {1}",
        "priceMax": "The total order price must be less than {0} {1}",
        "priceMinMax": "The total order price must be between {0} and {1} {2}",
        "dateMin": "Order date must be after {0}",
        "dateMax": "Order date must be before {0}",
        "dateMinMax": "Order date must be between {0} and {1}",
        "hourMin": "Order time must be after {0}",
        "hourMax": "Order time must be before {0}",
        "hourMinMax": "Order time must be between {0} and {1}",
        "maxItems": "Maximum number of elements reached",
        "restrictionApplies": "This product is not always available",
        "noAvail": "Sorry there is no slot available, try another time",
        "selectDeliveryModesToGetSlots": "Select a delivery method to display the slots.",
        "shareOnFacebook": "\"Share this product on facebook\"",
        "back": "Feedback",
        "poweredBy": "Site built with La Toque magique",
        "phoneInternational": "Phone number in international format +...",
        "demoDisclaim": "This is a demo site no orders will be honored",
        "manageMyAdresses": "Manage my addresses",
        "updateAddtionalInformation": "Update additional information",
        "updateCustomerDeliveryInformation": "Update delivery information for this address",
        "defineMainAdress": "Set my main address",
        "useMyAdresses": "Use my addresses",
        "useCustomAdresses": "Use another address",
        "backToHome": "Back to home page",
        "backNav": "Go back",
        "personalInformation": "Please fill your personal information",
        "seeInfo": "See useful information",
        "bookingadditionalInformationNotes": "Note for order",
        "bookingadditionalInformationNotesPlaceHolder": "Indicate for example \"Well-done meat\" or \"Without mayonnaise\", ...",
        "bookingadditionalInformation": "Information for the delivery or specific request for the order",
        "bookingadditionalInformationExample": "Building code, floor, intercom,…",
        "closed": "Establishment exceptionally closed",
        "new": "Nouveau",
        "starProducts": "top products",
        "mailSent": "Email sent",
        "mailSentDetail": "An email with your order details has been sent to {0}",
        "closingPeriod": "From {0} to {1}",
        "weekDay": "Day of the week",
        "closingDays": "Closing days",
        "schedules": "Schedule",
        "place": "Our location",
        "openingHours": "Opening hours",
        "contactUs": "Contact us",
        "unavailable": "Unavailable",
        "modifyMyAccount": "Modify my account",
        "homePageTitle": "Home",
        "infoContactPageTitle": "Useful information",
        "shopPageTitle": "Order",
        "profilePageTitle": "My account",
        "contactInfoPageTitle": "Useful information",
        "openingAndLocation": "Locations and times",
        "cartPageTitle": "See my basket",
        "creditCardDetail": "Credit card detail",
        "paymentCreditCard": "Pay by credit card now",
        "paymentDelivery": "Pay at reception",
        "paymentMethod": "Method of payment",
        "paymentMethodsForPickup": "Select your payment methods for cash on receipt",
        "saveChange": "Save changes",
        "backToProfile": "Back to my profile",
        "notificationInfo": "In order to receive notifications when your order is ready you can activate the notifications for this site, in the task bar of your browser",
        "activateNotification": "Enable notifications",
        "home": "Home",
        "orderCount": "Orders",
        "awaitingOrders": "Pending orders",
        "myProfile": "Mon profile",
        "seeMyOrderDetail": "See the status of my order",
        "orderCompletedThanks": "Thank you for ordering with {0}",
        "orderCompleted": "Order confirmed",
        "refresh": "Refresh",
        "deliveryEstimateDate": "Estimated delivery date: {0}",
        "orderDate": "Order date",
        "deliveryHour": "Expected delivery schedule",
        "pickupHour": "Scheduled pick-up time",
        "orderDetail": "Order details",
        "total": "Total",
        "mandatorySelection": "(Mandatory selection)",
        "optionListWithLimitMinMax": "Option {0} select minimum {1} option(s) and maximum {2} {3}",
        "optionListWithLimitMin": "Option {0} select minimum {1} option(s) {2}",
        "optionListWithLimitMax": "Option {0} select maximum {1} option(s) {2}",
        "optionListWithLimit": "Option {0} {1}",
        "mandatoryOption": "(OBLIGATORY)",
        "sendLinkAgain": "Resend activation link",
        "backToLoginPage": "Return to the login page",
        "createYourAccount": "create my account",
        "havingAnAccount": "I already have an account ?",
        "orderAgain": "Order again",
        "contentDeal": "Menu content",
        "modify": "Modifier",
        "editProfile": "Edit my account",
        "purchaseDate": "Order date",
        "orderNumber": "Order number",
        "orderNumberMobile": "N°",
        "orderId": "Order ID",
        "status": "Status",
        "dashBoard": "Dashboard",
        "orders": "Orders",
        "warning": "Warning",
        "infoMessage": "Information",
        "information": "Information",
        "viewAllCat": "See all categories",
        "backToCart": "Back to cart",
        "phone": "Phone",
        "bookWithoutAccount": "Order without creating an account",
        "profileInformation": "Account information",
        "tooFarAddress": "Address outside the delivery area",
        "formatDuration": "HH [hour(s) and] mm [minute(s)]",
        "formatDurationNoHour": "mm [minute(s)]",
        "distanceTime": "distance to property: {0} km / {1}",
        "distanceOnly": "distance to property: {0} km",
        "timeSlot": "Booking slot",
        "pickupSlot": "Recovery window",
        "selectDeliveryTimeSlot": "Select a delivery slot",
        "selectPickupTimeSlot": "Select a recovery window",
        "priceToPay": "Amount to be paid",
        "pricePaid": "Paid amount",
        "pendingPayment": "Payment pending",
        "remainingToPay": "Remains to pay: {0}",
        "totalNoTax": "Total hors taxes",
        "totalCharge": "Total costs",
        "totalTax": "Total VAT",
        "savedCode": "Savings with promo: {0}",
        "couponCode": "Promo code: {0}",
        "couponCodeSingle": "Promo code",
        "pointsSave": "{0} points",
        "totalTTC": "Total Incl. taxes",
        "deliveryFee": "Delivery costs",
        "deliveryFeeExternal": "External partner delivery costs",
        "totalFee": "Total costs",
        "deliverToOtherAddress": "Deliver to another address",
        "validateAdress": "Validate address",
        "clickAndCollect": "To be collected on site (Click N Collect)",
        "clickAndCollectSubTitle": "Collect your order without waiting at your point of sale",
        "delivery": "Delivery",
        "deliverySubTitle": "Have it delivered to your home, office or friends.",
        "deliveryMode": "Delivery method",
        "selectDeliveryMode": "Choose your delivery method",
        "cart": "Basket",
        "cartDesc": "Contents of your basket",
        "confirm": "Confirmation",
        "confirmAction": "Confirm",
        "order": "Order",
        "categories": "Categories",
        "menu": "Carte",
        "tags": "Tags",
        "selectDeal": "Choose the products",
        "choose": "Choose",
        "cancel": "Cancel",
        "next": "Select the next product",
        "select": "Select product",
        "addMenuToCart": "Add menu to cart",
        "checkOutNow": "Order now",
        "checkOutNowAndPayLater": "Order and pay {0}€ at the reception",
        "checkOutNowAndPayCard": "Order and pay {0}€ now",
        "orderFree": "Order for free!!",
        "continueShopping": "Add other products",
        "viewCart": "See cart details",
        "emptyBasket": "your basket is empty",
        "cartItemNumber": "{0} products in cart",
        "selectOptions": "Options",
        "deals": "Menu and offers",
        "sortBy": "sort by",
        "ourProducts": "Our products",
        "view": "Vue",
        "allCategories": "All categories",
        "category": "Category",
        "categorie": "Categories",
        "searchResults": "Search results for: {0}",
        "searchFor": "Search for a product....",
        "continueWithGoogle": "Login with google",
        "continueWithFaceook": "continue with facebook",
        "profile": "Profile",
        "profileDesc": "Information from your Profile",
        "myAccount": "My account",
        "myOrders": "My orders",
        "myAddresses": "My adresses",
        "addNewAddress": "add a new address",
        "modifyAddress": "Modify an address",
        "modifyMainAddress": "Change my main address",
        "mainAddress": "Main address",
        "backToAdress": "Back to my addresses",
        "nameAddress": "Address name",
        "updateMainAddress": "Update my primary address",
        "updateAddress": "Update address",
        "createAddress": "Create address",
        "account": "Account",
        "logout": "Sign out",
        "password": "Password",
        "reTypePassword": "Repeat password",
        "logEmailAndPassword": "Identify yourself",
        "dontHaveAccount": "You do not have an account?",
        "signup": "Create an account",
        "resetPassword": "Reset password",
        "forgotPassword": "Forgot your password",
        "address": "Address",
        "deliveryAdress": "Delivery address",
        "selectDeliveryAdress": "Choose delivery address",
        "email": "Email",
        "firstName": "First name",
        "lastName": "Nom",
        "termsAndConditions": "Terms and conditions",
        "activateAccount": "activate my account",
        "completeAccount": "Complete my account",
        "fillInfoToContinue": "Fill in the fields to continue",
        "login": "Login",
        "continueWithoutAccount": "No Thanks, Take my order without creating an account",
        "bySigningTermsAndConditions": "By checking this box you accept the terms and conditions",
        "requiredField": "The {0} field is required",
        "addToCart": "Add to Cart",
        "updateCart": "Edit Cart",
        "selectOptionsDetail": "Selectionner {0}",
        "description": "Description",
        "additionalInformation": "Additional information",
        "customerDeliveryInformation": "Additional information for delivery",
        "customerDeliveryInformationPlaceHolder": "Indicate here for example your door code, or other indications for the deliverer",
        "priceAsc": "Ascending price",
        "priceDesc": "\"Decreasing price\"",
        "orderSourceOnline": "online order",
        "orderSourceOffline": "restaurant order",
        "deliveryStatusOnGoing": "\"On going\"",
        "deliveryStatusNotStarted": "Not started",
        "deliveryStatusDone": "Done",
        "orderStatus": "Order status",
        "orderStatusNew": "Nouveau",
        "orderStatusPreparation": "Prepararation",
        "orderStatusReady": "Against",
        "orderStatusDelivering": "In delivery",
        "orderStatusComplete": "Finalized",
        "orderStatusFinished": "Ended",
        "paymentMethodsOffline": "Offline payment methods",
        "paymentMethodsOnline": "Online payment methods",
        "paymentMethodCash": "Cash",
        "paymentMethodCC": "Credit Card",
        "paymentMethodCheque": "Check",
        "paymentMethodTicket": "Ticket restaurant",
        "paymentMethodStripe": "Stripe",
        "day_0": "Monday",
        "day_1": "Tuesday",
        "day_2": "Wednesday",
        "day_3": "Thursday",
        "day_4": "Friday",
        "day_5": "Saturday",
        "day_6": "Sunday",
        "lunch": "lunch",
        "dinner": "dinner",
        "hrorderStatusNew": "Nouveau",
        "hrorderStatusReceived": "Received",
        "hrorderStatusAccepted": "Accepted",
        "hrorderStatusInPreparation": "En preparation",
        "hrorderStatusAwaitingShipment": "Ready to deliver",
        "hrorderStatusAwaitingCollection": "ready to recover",
        "hrorderStatusinDelivery": "shipping in progress",
        "hrorderStatusCompleted": "Finalized",
        "orderStatusPendingPayment": "Waiting for payment",
        "hrorderStatusRejected": "Rejected",
        "hrorderStatusCancelled": "Canceled",
        "hrorderStatusDeliveryFailed": "Delivery failure",
        "stuartFollowUrl": "\"Stuart tracking link\"",
        "stuartFollowUrlContent": "Click here to follow the progress of your order",
        "stuartLoadingTitle": "Verification of possibility of delivery",
        "stuartLoading": "We check if the delivery is possible",
        "check": {
            "fieldRequired": "The {0} field is required",
            "required": "Mandatory",
            "requiredField": "Required Field",
            "badPhoneFormat": "Invalid phone number",
            "termsAndConditionsMandatory": "You must accept the terms and conditions",
            "passwordsMatch": "Passwords must be the same",
            "reTypePassword": "Provide password again",
            "invalidEmail": "eMail invalide",
            "noDaySetting": "No slot configured",
            "noSelectPaymentMethod": "No payment method selected",
            "noSelectSlotMethod": "None Time slot selected",
            "noDeliveryAdress": "No delivery address selected",
            "maxDistanceReached": "The address is outside the zone",
            "noItemInCart": "\"No products in cart\"",
            "badContactInfo": "Invalid contact information",
            "deliveryMinPrice": "Insufficient amount for delivery",
            "pleaseAcceptCgv": "Please accept the terms and conditions"
        },
        "info": {
            "resetPassword": "An email has been sent to {0} to reset the password",
            "checkAddessInfo": "To find out if you are eligible for home delivery, please provide an address",
            "connectToOrder": "In order to keep track of your orders and to guarantee better follow-up, we advise you to place the order in online mode. If you have a Google account, It will only take a few seconds!!"
        },
        "warningMessage": {
            "noMainAddDefined": "Your main address is not defined",
            "maxDistanceDelivery": "The selected address is outside the delivery area but you can still order in click and collect mode",
            "maxDistanceDeliveryOk": "The selected address is in the delivery area",
            "maxDistanceDeliveryOkZone": "The selected address is in the delivery area ({0})",
            "selectValidDeliveryAddressAndSchedule": "Select a valid delivery address and a reservation window",
            "optionMandatory": "Please choose the required options",
            "minimalPriceForDeliveryNoReached": "\"Delivery is only available for a minimum amount of {0} €\"",
            "deliveryUnavailable": "Delivery not available",
            "paymentIssue": "There was a problem with your payment",
            "profileNotActivated": "Your account is not yet active, check your email and activate your account by clicking on the link contained in the activation email, then log in again",
            "deliveryFeeOccurs": "Delivery costs at your expense amount to {0} {1}",
            "stuartDeliveryPossible": "Delivery available!",
            "stuartDeliveryImpossible": "Delivery not available!",
            "stuartConnectionIssue": "We are having problems communicating with the external delivery service",
            "stuartOutOfRange": "The delivery address is outside the covered area"
        },
        "notif": {
            "accountCreated": "Account created",
            "dealAddedToCart": "Offer added to cart",
            "productAddedToCart": "Product added to shopping cart",
            "activationEmailSentNotif": "Activation email sent to {0}, check your email, activate the account then log in again"
        },
        "notifForBackEnd": {
            "orderCreated": "New Online Order: {0}"
        },
        "errorMessages": {
            "accountAlreadyExists": "This account is already referenced, try to connect directly using this email",
            "wrongPassword": "Invalid password",
            "noUserEmail": "\"No account found with this email\""
        },
        "confirmMessage": {
            "deleteAddress": "Are you sure you want to delete this address ?",
            "deleteReview": "Are you sure you want to delete this review?"
        },
        "emailTemplate": {
            "passwordReset": "Click <a href=\"{0}\">here</a> to reset your password {1}",
            "activateEmail": "Click <a href=\"{0}\">here</a> to activate your account {1}",
            "passwordResetSubject": "Reset your password {0}",
            "activateEmailSubject": "Activate your account {0}"
        },
        "allergens": "Allergens",
        "allergenTypes": {
            "gluten": "Gluten",
            "shellfish": "Shellfish",
            "egg": "Egg",
            "fishes": "Pisces",
            "peanuts": "Peanuts",
            "soy": "Military",
            "milk": "Lait",
            "nuts": "Nuts",
            "celery": "Fast",
            "mustard": "Mustard",
            "sesameSeeds": "Sesame seeds",
            "sulfurDioxideSulphites": "Sulfur dioxide and sulphites",
            "lupine": "Lupin",
            "molluscs": "molluscs"
        }
    }
});

export default localStrings;
